# Configuración simplificada del Pipeline RAG para prueba
# Versión: 1.0.0-test
# Fecha: 2025-06-06

# Configuración general del pipeline
general:
  name: "MineduRAGPipeline-Test"
  version: "1.0.0-test"
  domain: "legal"
  country: "peru"
  language: "es"
  description: "Pipeline RAG para prueba de sanity check"

# Configuración de chunking de documentos
chunking:
  chunk_size: 1000
  chunk_overlap: 200
  split_by: "paragraph"
  add_metadata: true
  metadata_fields:
    - "source"
    - "title"

# Configuración del BM25 Retriever (único componente habilitado)
bm25_retriever:
  enabled: true
  index_path: "data/indices/bm25_index"
  k: 5
  b: 0.75
  k1: 1.5
  use_stemming: true
  remove_stopwords: true
  language: "spanish"
  score_threshold: 0.3

# Configuración del Dense Retriever (deshabilitado para prueba)
dense_retriever:
  enabled: false
  model_name: "intfloat/multilingual-e5-large"
  vector_store: "chroma"
  vector_store_path: "data/indices/chroma_minedu"
  embedding_device: "cpu"  # Cambiado a CPU para prueba
  k: 5

# Configuración de la fusión híbrida (deshabilitada para prueba)
hybrid_fusion:
  enabled: false
  method: "rrf"
  rrf_k: 60
  weights:
    bm25: 1.0
    dense: 0.0

# Configuración del Neural Reranker (deshabilitado para prueba)
neural_reranker:
  enabled: false
  model_name: "cross-encoder/ms-marco-MiniLM-L-12-v2"
  device: "cpu"  # Cambiado a CPU para prueba
  k: 3

# Configuración de métricas y evaluación
evaluation:
  metrics:
    - "token_overlap"
    - "exact_match"
  dataset_path: "paper_cientifico/dataset/golden_dataset.json"
  results_path: "paper_cientifico/results/test_results.json"
  log_level: "info"
  track_latency: true
  track_memory: false
  track_tokens: false

# Configuración de logging
logging:
  level: "info"
  file: "logs/minedu_rag_test.log"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  console: true
  file_rotation: false
