# Configuración del Pipeline RAG para MINEDU
# Versión: 1.0.0
# Fecha: 2025-06-05

# Configuración general del pipeline
general:
  name: "MineduRAGPipeline"
  version: "1.0.0"
  domain: "legal"
  country: "peru"
  language: "es"
  description: "Pipeline RAG para consultas normativas legales de MINEDU"

# Configuración de chunking de documentos
chunking:
  chunk_size: 1000
  chunk_overlap: 200
  split_by: "paragraph"
  add_metadata: true
  metadata_fields:
    - "source"
    - "title"
    - "date"
    - "category"

# Configuración del BM25 Retriever
bm25_retriever:
  enabled: true
  index_path: "data/indices/bm25_index"
  k: 10
  b: 0.75
  k1: 1.5
  use_stemming: true
  remove_stopwords: true
  language: "spanish"
  score_threshold: 0.3

# Configuración del Dense Retriever (E5-Large)
dense_retriever:
  enabled: true
  model_name: "intfloat/multilingual-e5-large"
  vector_store: "chroma"
  vector_store_path: "data/indices/chroma_minedu"
  embedding_device: "cuda"
  embedding_batch_size: 32
  k: 10
  score_threshold: 0.6
  normalize_embeddings: true
  cache_embeddings: true

# Configuración de la fusión híbrida (RRF)
hybrid_fusion:
  enabled: true
  method: "rrf"
  rrf_k: 60
  weights:
    bm25: 0.4
    dense: 0.6
  k: 8
  rerank_threshold: 0.5
  deduplication: true
  deduplication_threshold: 0.92

# Configuración del Neural Reranker (CrossEncoder)
neural_reranker:
  enabled: true
  model_name: "cross-encoder/ms-marco-MiniLM-L-12-v2"
  device: "cuda"
  batch_size: 16
  k: 5
  score_threshold: 0.6
  cache_scores: true

# Configuración de métricas y evaluación
evaluation:
  metrics:
    - "faithfulness"
    - "answer_relevancy"
    - "context_precision"
    - "context_recall"
    - "token_overlap"
    - "exact_match"
  dataset_path: "paper_cientifico/dataset/golden_dataset.json"
  results_path: "paper_cientifico/results/evaluation_results.json"
  log_level: "info"
  track_latency: true
  track_memory: true
  track_tokens: true

# Configuración de logging
logging:
  level: "info"
  file: "logs/minedu_rag.log"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  console: true
  file_rotation: true
  max_file_size: 10485760  # 10MB

# Configuración de estudios de ablación
ablation:
  variations:
    - name: "only_bm25"
      components:
        bm25_retriever: true
        dense_retriever: false
        hybrid_fusion: false
        neural_reranker: false
    - name: "only_dense"
      components:
        bm25_retriever: false
        dense_retriever: true
        hybrid_fusion: false
        neural_reranker: false
    - name: "hybrid_no_rerank"
      components:
        bm25_retriever: true
        dense_retriever: true
        hybrid_fusion: true
        neural_reranker: false
    - name: "full_pipeline"
      components:
        bm25_retriever: true
        dense_retriever: true
        hybrid_fusion: true
        neural_reranker: true
  chunk_variations:
    - chunk_size: 500
      chunk_overlap: 100
    - chunk_size: 1000
      chunk_overlap: 200
    - chunk_size: 1500
      chunk_overlap: 300
  fusion_weight_variations:
    - bm25: 0.3
      dense: 0.7
    - bm25: 0.5
      dense: 0.5
    - bm25: 0.7
      dense: 0.3
