plugins:
  - id: "audio-transcription"
    name: "Transcripción de Audio"
    description: "Convierte audio a texto usando Whisper"
    version: "1.0.0"
    capabilities: ["audio_processing"]
    endpoint: "/api/plugins/audio/transcribe"
    enabled: true
    auth_required: true
    max_file_size_mb: 25
    timeout_seconds: 120
    rate_limit_per_minute: 10
    config:
      model: "whisper-1"
      language: "es"
      response_format: "json"

  - id: "document-ocr"
    name: "OCR de Documentos"
    description: "Extrae texto de imágenes y PDFs"
    version: "1.2.0"
    capabilities: ["vision_processing", "document_analysis"]
    endpoint: "/api/plugins/ocr/extract"
    enabled: true
    auth_required: true
    max_file_size_mb: 50
    timeout_seconds: 60
    rate_limit_per_minute: 30
    config:
      supported_formats: ["pdf", "png", "jpg", "jpeg", "tiff"]
      dpi: 300
      language: "spa"

  - id: "entity-extraction"
    name: "Extracción de Entidades"
    description: "Identifica y extrae entidades específicas de documentos"
    version: "1.1.0"
    capabilities: ["nlp_processing", "entity_recognition"]
    endpoint: "/api/plugins/entities/extract"
    enabled: true
    auth_required: true
    max_file_size_mb: 10
    timeout_seconds: 30
    rate_limit_per_minute: 60
    config:
      entities: ["PERSON", "ORG", "MONEY", "DATE", "PROCEDURE"]
      confidence_threshold: 0.8

  - id: "document-classifier"
    name: "Clasificador de Documentos"
    description: "Clasifica documentos por tipo y confidencialidad"
    version: "1.0.1"
    capabilities: ["classification", "security_analysis"]
    endpoint: "/api/plugins/classify/document"
    enabled: true
    auth_required: true
    max_file_size_mb: 20
    timeout_seconds: 45
    rate_limit_per_minute: 40
    config:
      categories: ["directiva", "resolucion", "oficio", "memorandum"]
      security_levels: ["publico", "reservado", "confidencial"]